* use pmnewdiff for new files, so that new files are not stored as "originals" but rather as VCDIFF, including compression

diff --git a/patchmonger b/patchmonger
--- a/patchmonger
+++ b/patchmonger
@@ -14,7 +14,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-VERSION="0.1.2"
+VERSION="0.2.0"
 
 function header {
   echo "                                "
@@ -100,9 +100,13 @@ function create-patch {
       echo -n "n"
       [ "$VERBOSE" ] && echo " Adding new file $FILE"
       mkdir -p "$PATCHDATA/$FILE_DIR"
-      cp --preserve=mode "$NEW/$FILE" "$PATCHDATA/$FILE.pmnew"
+      touch "$PATCHDATA/$FILE"
+      xdelta3 -D -R -S lzma -s "$PATCHDATA/$FILE" "$NEW/$FILE" "$PATCHDATA/$FILE.pmnewdiff"
+      rm "$PATCHDATA/$FILE"
+      PATCH_FILEPERM=$(stat -c "%a" "$NEW/$FILE")
+      chmod "$PATCH_FILEPERM" "$PATCHDATA/$FILE.pmnewdiff"
       STATUS=$?
-      [ $STATUS -ne 0 ] && error "Cannot create $PATCHDATA/$FILE.pmnew"
+      [ $STATUS -ne 0 ] && error "Cannot create $PATCHDATA/$FILE.pmnewdiff"
     else
       MD5_NEW=($(md5sum "$NEW/$FILE"))
       MD5_OLD=($(md5sum "$OLD/$FILE"))
@@ -110,7 +114,7 @@ function create-patch {
         echo -n "p"
         [ "$VERBOSE" ] && echo "Creating xdelta3 diff for $FILE"
         mkdir -p "$PATCHDATA/$FILE_DIR"
-        xdelta3 -S lzma -s "$OLD/$FILE" "$NEW/$FILE" "$PATCHDATA/$FILE.pmdiff"
+        xdelta3 -D -R -S lzma -s "$OLD/$FILE" "$NEW/$FILE" "$PATCHDATA/$FILE.pmdiff"
         STATUS=$?
         [ $STATUS -ne 0 ] && error "Cannot create $PATCHDATA/$FILE.pmdiff"
       fi
@@ -151,12 +155,20 @@ function apply-patch {
   DOT_COUNTER=0
   while IFS= read -r -d '' FILE; do
     FILE_DIR=$(dirname "$FILE")
-    PATCH_TYPE=$(echo $FILE | sed 's/.*\.\(pmdiff\|pmdel\|pmnew\)$/\1/')
-    PATCH_FILENAME=$(echo $FILE | sed 's/\(.*\)\.\(pmdiff\|pmdel\|pmnew\)$/\1/')
+    PATCH_TYPE=$(echo $FILE | sed 's/.*\.\(pmdiff\|pmdel\|pmnew\|pmnewdiff\)$/\1/')
+    PATCH_FILENAME=$(echo $FILE | sed 's/\(.*\)\.\(pmdiff\|pmdel\|pmnew\|pmnewdiff\)$/\1/')
     case "$PATCH_TYPE" in
       pmdiff)
         if [ ! -e "$DST/$PATCH_FILENAME" ]; then
           MSG="File $DST/$PATCH_FILENAME not found!"
+          echo
+          [ -z "$FORCE" ] && error "$MSG"
+          warn "$MSG"
+        fi
+      ;;
+      pmnewdiff)
+        if [ -e "$DST/$PATCH_FILENAME" ]; then
+          MSG="File $DST/$PATCH_FILENAME already exists!"
           echo
           [ -z "$FORCE" ] && error "$MSG"
           warn "$MSG"
@@ -177,7 +189,7 @@ function apply-patch {
       echo -n "."
       DOT_COUNTER=0
     fi
-  done < <(find . -type f \( -name \*.pmdiff -o -name \*.pmdel -o -name \*.pmnew \) -print0)
+  done < <(find . -type f \( -name \*.pmdiff -o -name \*.pmdel -o -name \*.pmnew -o -name \*.pmnewdiff \) -print0)
   echo "ok"
   popd >/dev/null
 
@@ -185,13 +197,13 @@ function apply-patch {
   pushd "$SRC" >/dev/null
   while IFS= read -r -d '' FILE; do
     FILE_DIR=$(dirname "$FILE")
-    PATCH_TYPE=$(echo $FILE | sed 's/.*\.\(pmdiff\|pmdel\|pmnew\)$/\1/')
-    PATCH_FILENAME=$(echo $FILE | sed 's/\(.*\)\.\(pmdiff\|pmdel\|pmnew\)$/\1/')
+    PATCH_TYPE=$(echo $FILE | sed 's/.*\.\(pmdiff\|pmdel\|pmnew\|pmnewdiff\)$/\1/')
+    PATCH_FILENAME=$(echo $FILE | sed 's/\(.*\)\.\(pmdiff\|pmdel\|pmnew\|pmnewdiff\)$/\1/')
     case "$PATCH_TYPE" in
       pmdiff)
         echo -n "p"
         [ "$VERBOSE" ] && echo "Applying diff to $DST/$PATCH_FILENAME"
-        xdelta3 -d -s "$DST/$PATCH_FILENAME" "$SRC/$FILE" "$DST/$PATCH_FILENAME.patched"
+        xdelta3 -D -R -d -s "$DST/$PATCH_FILENAME" "$SRC/$FILE" "$DST/$PATCH_FILENAME.patched"
         STATUS=$?
         if [ $STATUS -ne 0 ]; then
           MSG="Cannot apply xdelta patch to $DST/$PATCH_FILENAME"
@@ -200,6 +212,24 @@ function apply-patch {
           warn "$MSG"
         else
           PATCH_FILEPERM=$(stat -c "%a" "$DST/$PATCH_FILENAME")
+          mv "$DST/$PATCH_FILENAME.patched" "$DST/$PATCH_FILENAME"
+          chmod "$PATCH_FILEPERM" "$DST/$PATCH_FILENAME"
+        fi
+      ;;
+      pmnewdiff)
+        echo -n "n"
+        [ "$VERBOSE" ] && echo "Generating new file from diff $DST/$PATCH_FILENAME"
+        rm -f "$DST/$PATCH_FILENAME"
+        touch "$DST/$PATCH_FILENAME"
+        xdelta3 -D -R -d -s "$DST/$PATCH_FILENAME" "$SRC/$FILE" "$DST/$PATCH_FILENAME.patched"
+        STATUS=$?
+        if [ $STATUS -ne 0 ]; then
+          MSG="Cannot apply xdelta patch to $DST/$PATCH_FILENAME"
+          echo
+          [ -z "$FORCE" ] && error "$MSG"
+          warn "$MSG"
+        else
+          PATCH_FILEPERM=$(stat -c "%a" "$SRC/$FILE")
           mv "$DST/$PATCH_FILENAME.patched" "$DST/$PATCH_FILENAME"
           chmod "$PATCH_FILEPERM" "$DST/$PATCH_FILENAME"
         fi
@@ -229,7 +259,7 @@ function apply-patch {
         fi
       ;;
     esac
-  done < <(find . -type f \( -name \*.pmdiff -o -name \*.pmdel -o -name \*.pmnew \) -print0)
+  done < <(find . -type f \( -name \*.pmdiff -o -name \*.pmdel -o -name \*.pmnew -o -name \*.pmnewdiff \) -print0)
   echo
   echo "Finished!"
   popd >/dev/null
